### PR TITLE
Wagtail 6.0 support

### LINKED ISSUE #31: Wagtail 6.0 support
Haven't tested whether anything breaks in Wagtail 6.0, but I wouldn't be surprised if there are issues given the template changes in 6.0.

~~Should probably set up a nightly build to notify any test failures as well.~~ Just need to get the Slack webhook URL...

### PR DESCRIPTION
**Pull request by gasman**
Towards #31

### CODE REVIEW

**Review by lb- — APPROVED** [review]
Looks good to me.

**Comment by gasman** [comment]
Worth noting that this is also the root cause of the current test failures on wagtail-localize - all wagtail-localize tests pass when run against a patched modeladmin.

**Comment by lb-** [comment]
Just took another look. Changes make sense. Not sure if you wanted to wait for a review from Sage though.

**Review by laymonage — APPROVED** [review]
Thanks! I think we should drop support for Django <4.2 and Wagtail <5.2, I'll do that separately.

**Review by laymonage — COMMENTED** [review]
Just want to note that while this fixes the crash, the UI is broken due to other changes to the listing styles in 6.0:

image

I'll fix this separately.

**Pull request merged**
